export enum EActionTypes {
  LOAD_RESULTS_REQUEST = 'MAIN/LOAD_RESULTS_REQUEST',
  LOAD_RESULTS_SUCCESS = 'MAIN/LOAD_RESULTS_SUCCESS',
  LOAD_RESULTS_FAILURE = 'MAIN/LOAD_RESULTS_FAILURE',

  SET_TASK_IDS = 'MAIN/SET_TASK_IDS',
  SET_TASK_STATUS = 'MAIN/SET_TASK_STATUS',
}
